models:
  - name: dim_hosts_cleansed
    columns:
      - name: host_id
        data_tests:
          - not_null
          - unique

      - name: host_name
        data_tests:
          - not_null

      - name: is_superhost
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f'] 

